/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebapf;

import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import java.awt.Toolkit;
import java.awt.Color;

/**
 *
 * @author fermu
 */
public class ventanaAltaTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form ventanaAltaTarjeta
     */

	ArrayList<String> arreComponentes = new ArrayList();
	String componentes;
	String cantidades;
	
    public ventanaAltaTarjeta() {
    	getContentPane().setBackground(new Color(255, 239, 213));
    	setResizable(false);
    	setIconImage(Toolkit.getDefaultToolkit().getImage(ventanaAltaTarjeta.class.getResource("/pruebapf/drakkar.png")));
        initComponents();
        InventarioControlador inv = new InventarioControlador();
    	coboComponente =  inv.llenaComponentes(coboComponente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnRegresar.setBackground(new Color(255, 255, 255));
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        coboComponente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        spinnerCantidad = new javax.swing.JSpinner();
        btnAgregarComponente = new javax.swing.JButton();
        btnAgregarComponente.setBackground(new Color(255, 255, 255));
        btnAltaTarjeta = new javax.swing.JButton();
        btnAltaTarjeta.setBackground(new Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("alta de tarjeta generica");
        setLocation(new java.awt.Point(400, 50));

        btnRegresar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnRegresar.setText("regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("nombre");

        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("componentes");

        coboComponente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("cantidad");

        spinnerCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100000, 1));

        btnAgregarComponente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnAgregarComponente.setText("agregar componente");
        btnAgregarComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComponenteActionPerformed(evt);
            }
        });

        btnAltaTarjeta.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnAltaTarjeta.setText("dar tarjeta de alta");
        btnAltaTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaTarjetaActionPerformed(evt);
            }
        });
        jList1 = new javax.swing.JList<>();
        jList1.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        
        JLabel lblNewLabel = new JLabel("clave");
        lblNewLabel.setFont(new Font("Comic Sans MS", Font.PLAIN, 12));
        
        txtClave = new JTextField();
        txtClave.setFont(new Font("Comic Sans MS", Font.PLAIN, 12));
        txtClave.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(81)
        							.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(59)
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.RELATED)))
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(coboComponente, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(txtNombre, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        					.addGap(55)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel3)
        						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(18)
        							.addComponent(spinnerCantidad, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(txtClave, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(btnRegresar)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btnAgregarComponente)
        				.addComponent(btnAltaTarjeta))
        			.addContainerGap(256, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(215)
        			.addComponent(jList1, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(477, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel)
        				.addComponent(txtClave, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(coboComponente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2)
        				.addComponent(jLabel3)
        				.addComponent(spinnerCantidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnAgregarComponente))
        			.addGap(28)
        			.addComponent(jList1, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
        			.addGap(38)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnRegresar)
        				.addComponent(btnAltaTarjeta))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ventanaTrabajador vT = new ventanaTrabajador();
        vT.setVisible(true);
        this.dispose();
    }

    private void btnAgregarComponenteActionPerformed(java.awt.event.ActionEvent evt) 
    {
        txtNombre.setEnabled(false);
        txtClave.setEnabled(false);
        String[] aux = coboComponente.getSelectedItem().toString().split(",");
        if(arreComponentes.size() < 1)
        {
        	componentes = aux[1];
        	cantidades = spinnerCantidad.getValue().toString();
        }
        else
        {
        	componentes = componentes + "," + aux[1];
        	cantidades = cantidades + "," + spinnerCantidad.getValue().toString();
        }
        
        arreComponentes.add(coboComponente.getSelectedItem().toString() + " : " + spinnerCantidad.getValue().toString());
        DefaultListModel<String> modelo = new DefaultListModel<>();
        jList1.setModel(modelo);
        for(int i = 0; i < arreComponentes.size(); i++)
        {
        	modelo.addElement(arreComponentes.get(i)); 
        }
        coboComponente.setSelectedIndex(0);
        spinnerCantidad.setValue(1);
    }

    private void btnAltaTarjetaActionPerformed(java.awt.event.ActionEvent evt) 
    {
    	boolean siono;
    	InventarioControlador iC = new InventarioControlador();
    	siono = iC.AltaTarjeta(txtNombre.getText(), componentes, cantidades, Integer.parseInt(txtClave.getText()));
    	if(siono == true)
    		JOptionPane.showMessageDialog(null, "tarjeta dada de alta");
    	else
    		JOptionPane.showMessageDialog(null, "error al dar de alta la tarjeta");
        DefaultListModel<String> modelo = new DefaultListModel<>();
        arreComponentes.clear();
        jList1.setModel(modelo);
        txtNombre.setText("");
        txtNombre.setEnabled(true);
        txtClave.setText("");
        txtClave.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarComponente;
    private javax.swing.JButton btnAltaTarjeta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> coboComponente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JTextField txtNombre;
    private JTextField txtClave;
}
