/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebapf;

import java.awt.Dimension;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.SwingConstants;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author fermu
 */
public class ventanaDescontarComponentes extends javax.swing.JFrame {

    
    JFrame reg;
    public ventanaDescontarComponentes(boolean maquilador) 
    {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(ventanaDescontarComponentes.class.getResource("/pruebapf/drakkar.png")));
    	getContentPane().setBackground(new Color(255, 239, 213));
    	
        //true = maquilador        false = trabajador
        initComponents();
        InventarioControlador inv = new InventarioControlador();
    	comboComponente = inv.llenaComponentes(comboComponente);
        if(maquilador == true)
        {
            reg = new ventanaMaquilador();
        }
        else
            reg = new ventanaTrabajador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnRegresar.setBackground(new Color(255, 255, 255));
        jLabel1 = new javax.swing.JLabel();
        comboComponente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        spinnerCantidad = new javax.swing.JSpinner();
        btnDescontar = new javax.swing.JButton();
        btnDescontar.setBackground(new Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("descontar componentes");
        setLocation(new java.awt.Point(400, 50));
        setPreferredSize(new Dimension(500,400));
        setResizable(true);

        btnRegresar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnRegresar.setText("regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("componente");

        comboComponente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("cantidad");

        spinnerCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100000, 1));

        btnDescontar.setFont(new Font("Comic Sans MS", Font.PLAIN, 16)); // NOI18N
        btnDescontar.setText("descontar ");
        btnDescontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontarActionPerformed(evt);
            }
        });
        
        lblDescuentoInventario = new JLabel("descuento inventario");
        lblDescuentoInventario.setHorizontalAlignment(SwingConstants.CENTER);
        lblDescuentoInventario.setFont(new Font("Comic Sans MS", Font.PLAIN, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(btnRegresar)
        			.addContainerGap(146, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(102, Short.MAX_VALUE)
        			.addComponent(lblDescuentoInventario, GroupLayout.PREFERRED_SIZE, 287, GroupLayout.PREFERRED_SIZE)
        			.addGap(97))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(65)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(comboComponente, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
        			.addGap(28)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(spinnerCantidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(56, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(186, Short.MAX_VALUE)
        			.addComponent(btnDescontar, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
        			.addGap(175))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(52)
        			.addComponent(lblDescuentoInventario, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addGap(49)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(comboComponente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1)
        				.addComponent(jLabel2)
        				.addComponent(spinnerCantidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(59)
        			.addComponent(btnDescontar)
        			.addPreferredGap(ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
        			.addComponent(btnRegresar)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnDescontarActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_btnDescontarActionPerformed
    	boolean siono;
    	InventarioControlador iC = new InventarioControlador();
    	System.out.println(comboComponente.getItemAt(comboComponente.getSelectedIndex()));
    	siono = iC.QuitarPieza(comboComponente.getItemAt(comboComponente.getSelectedIndex()), Integer.parseInt(spinnerCantidad.getValue().toString()));
    	if(siono == true)
    		JOptionPane.showMessageDialog(null, "componentes descontados del inventario");
    	else
    		JOptionPane.showMessageDialog(null, "error al descontar componentes");
        comboComponente.setSelectedIndex(0);
        spinnerCantidad.setValue(1);
    }//GEN-LAST:event_btnDescontarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescontar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboComponente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spinnerCantidad;
    private JLabel lblDescuentoInventario;
    // End of variables declaration//GEN-END:variables
}
